apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: testing
  name: testing
spec:
  containers:
  - image: nginx
    name: testing
    resources: {}
    command: [ "/bin/bash", "-c", "--" ]
    args: [ "while true; do sleep 30; done;" ]
